# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ZcrkgXui57fHh9EWgo7fyFeYQTVgCFc/AQNHhmbp3qC/EcvQ2ys3OWlhEEbnqai4rT4XCnOb/G7RyVkkYA2TgaQyAb9nOlm2krzCZ9uj84NXU9qBIjt1rsYA87SL0zutFhFUr5fRYKyV6nLGA/aWuVbn5iRuszZZyatpPliWdgkxqX5bLOS6QupL0HKzMEcGtsVkuCAXp22ZMtE7raT6UhBmCFTOxuP965peVv1UBHAGkOXdudWoO++dONaaHwcaaLa7Kf7n15tAyt4lA6e0bM+kJ+YTOBLEbKEiXYTiO5Bxzk1oq7S+jtPf0yEx4sKn/wklAbmlZW9uZpgbIMOmbtF7Gto/hSkqQGXc+HaMZqPyTKzfI9Q47AjhDur9T5kKzLYfCHqpg4fDutBq0XtyKyGtyl6e8AnIRNzo5Dt+Z3Fs9KrVgFnl2UoBEKZWZJi6rIF2oGgzzmzJzbZ8ev5faPaUDyCRT3ul0in5Wc9qOMO133AeQoaSopz0Cl5pQbwlPaWj3xFkIBUI9UAFoTsaqgOye+tqa0Ym+K/CaNGEnPACMvjXi+K2Ii+FblolktShYOIY/J+swpRmeZhgohtmrirbePJeQzGAOlpoyZLMXrCEk5vjV33ZehP1PYMOVsg1yEL45dXL9Y3j/qIIkdp4Dav2EbSL185hME19h+lrHec="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_target_platformlinux-ppc64le UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux-ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.travis/run_docker_build.sh; fi